### ISSUE TITLE
FactoryGirl runs factories after rails initializes?

### ISSUE THREAD

**Issue by hakunin** [thoughtbot/factory_bot_rails#178]
Hi, it seems that FactoryGirl when used with Spring tries to run some factories when the app starts.

Which is super strange and breaks running my migrations. 

Let me know how I can help debugging it.

Using version `4.5.0`.

```
   (0.2ms)  BEGIN
  SQL (0.5ms)  INSERT INTO "organizations" ("name", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["name", "Kuhic, Mitchell and Kunde"], ["created_at", "2015-10-27 16:47:10.116676"], ["updated_at", "2015-10-27 16:47:10.116676"]]
   (0.4ms)  COMMIT
   (0.4ms)  BEGIN
  User Exists (1.4ms)  SELECT  1 AS one FROM "users" WHERE "users"."email" = 'polly.fadel@lowe.biz' LIMIT 1
   (0.3ms)  ROLLBACK
rake aborted!
NoMethodError: undefined method `screen_name' for #<User:0x00000112f985e0>
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/michal/dev/myproject/app/models/user.rb:91:in `prefill_screen_name'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `call'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `block in halting'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/callbacks.rb:302:in `create_or_update'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/persistence.rb:142:in `save!'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/validations.rb:43:in `save!'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `block in save!'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/transactions.rb:291:in `save!'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/Users/michal/dev/myproject/test/factories/organization.rb:10:in `block (4 levels) in <top (required)>'
/Users/michal/dev/myproject/test/factories/organization.rb:9:in `times'
/Users/michal/dev/myproject/test/factories/organization.rb:9:in `block (3 levels) in <top (required)>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/callback.rb:13:in `instance_exec'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/callback.rb:13:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/callbacks_observer.rb:11:in `block in update'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/callbacks_observer.rb:10:in `each'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/callbacks_observer.rb:10:in `update'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:20:in `notify'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:13:in `block in result'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:5:in `association'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluator.rb:31:in `association'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute/association.rb:19:in `block in to_proc'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluator.rb:71:in `instance_exec'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluator.rb:71:in `block in define_attribute'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:56:in `get'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:12:in `object'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/Users/michal/dev/myproject/test/factories/work_package.rb:4:in `block (2 levels) in <top (required)>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/Users/michal/dev/myproject/test/factories/work_package.rb:3:in `block in <top (required)>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
/Users/michal/dev/myproject/test/factories/work_package.rb:2:in `<top (required)>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:19:in `each'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `each'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `call'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `each'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/Users/michal/dev/myproject/config/environment.rb:5:in `<top (required)>'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/skylight-0.8.0/lib/skylight/probes.rb:81:in `require'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/skylight-0.8.0/lib/skylight/probes.rb:81:in `require'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/Users/michal/.rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
```

**Comment by dansteele** [comment]
This also happens for me, using Rails **5.0.0rc1**

Have actually had to comment out FactoryGirl to run migrations

Proof factories are run on init
```
2.3.0 :002 > Pilot.count
   (0.8ms)  SELECT COUNT(*) FROM "pilots"
 => 2 
2.3.0 :003 > 
daniel@daniel-P170EM:~/projects/projects_omnidev/atc123$ rails c
Loading development environment (Rails 5.0.0.rc1)
2.3.0 :001 > Pilot.count
   (0.8ms)  SELECT COUNT(*) FROM "pilots"
 => 3 
```
Example factory in `spec/factories/pilot_factory`
```ruby
FactoryGirl.define do
  factory :pilot do
    first_name {Faker::Name.first_name}
    last_name {Faker::Name.last_name}
    email {Faker::Internet.email}
    password "password"
    password_confirmation "password"
  end
end
```

I've used FactoryGirl in pretty much every project I've done, and only had this issue with Rails 5

**Comment by joshuaclayton** [comment]
@hakunin can you provide the factory code for `test/factories/organization.rb`, `test/factories/work_package.rb`, and `config/environment.rb`? It looks like there's something that's automatically executing factories.

@dansteele Can you do the same? FG doesn't go out of its way to run any factories at all. Pieces that might automatically run factories include a db:seeds task or linting factories, but neither are triggered explicitly just because it's the latest RC of Rails.

Can you attempt to reproduce this in a brand new repository with the latest RC of Rails and a couple of bare-bones factories and point me at the repository so I can do some investigation?

**Comment by dansteele** [comment]
@joshuaclayton 
I created a new repo with Rails 5, and there were no issues. The issue, however, may have arisen since I was upgrading from 4.2.x => 5
When I uncomment the gem now, I get a different issue to earlier on, though it does seem to be quite related. Here's the stack trace:
```
daniel@daniel-P170EM:~/projects/projects_omnidev/atc123$ rails s
=> Booting WEBrick
=> Rails 5.0.0.rc1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/registry.rb:24:in `find': Factory not registered: pilot (ArgumentError)
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/decorator.rb:10:in `method_missing'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl.rb:85:in `factory_by_name'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/factory_runner.rb:12:in `run'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
	from /home/daniel/projects/projects_omnidev/atc123/spec/factories/flight_factory.rb:3:in `block (2 levels) in <top (required)>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:18:in `factory'
	from /home/daniel/projects/projects_omnidev/atc123/spec/factories/flight_factory.rb:2:in `block in <top (required)>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:49:in `run'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/syntax/default.rb:7:in `define'
	from /home/daniel/projects/projects_omnidev/atc123/spec/factories/flight_factory.rb:1:in `<top (required)>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:287:in `load'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:19:in `each'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:15:in `each'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl-4.7.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/factory_girl_rails-4.7.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:30:in `run'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /home/daniel/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/application.rb:352:in `initialize!'
	from /home/daniel/projects/projects_omnidev/atc123/config/environment.rb:5:in `<top (required)>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `block in require'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0.rc1/lib/active_support/dependencies.rb:293:in `require'
	from /home/daniel/projects/projects_omnidev/atc123/config.ru:3:in `block in <main>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:55:in `instance_eval'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:55:in `initialize'
	from /home/daniel/projects/projects_omnidev/atc123/config.ru:in `new'
	from /home/daniel/projects/projects_omnidev/atc123/config.ru:in `<main>'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:49:in `eval'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:49:in `new_from_string'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/builder.rb:40:in `parse_file'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/server.rb:218:in `app'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/server.rb:59:in `app'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/rack-2.0.0.rc1/lib/rack/server.rb:353:in `wrapped_app'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/server.rb:77:in `start'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/daniel/.rvm/gems/ruby-2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```
From what I can tell, this is the hook that's reading in the factories https://github.com/thoughtbot/factory_girl_rails/blob/master/lib/factory_girl_rails/railtie.rb#L21

I do also have a factory in `spec/factories/pilot_factory.rb`
```ruby
FactoryGirl.define do
  factory :pilot do
    first_name {Faker::Name.first_name}
    last_name {Faker::Name.last_name}
    email {Faker::Internet.email}
    password "password"
    password_confirmation "password"
  end
end
```
I'm going to continue trying to dig around

**Comment by joshuaclayton** [comment]
@dansteele hmm. What's in `spec/factories/flight_factory.rb`? Looks like that's what's triggering snagging `pilot`.

**Comment by dansteele** [comment]
@joshuaclayton 
I had `pilot_id FactoryGirl::create :pilot`. If I change this to `pilot_id 1` instead, then the server fires up again, but the duplication issue occurs again.

I'm not sure if it's standard, but I've had factories user other factories before

That would suggest to me that the flight_factory is being read in _and evaluated_ before pilot_factory is read in. But not sure why

**Comment by joshuaclayton** [comment]
@dansteele if it's a standard Rails association, you should be able to do:

```ruby
factory :flight do
  pilot
  # .. everything else
end
```

And it will manage the association correctly.

The reason why this is failing for you is because it's evaluating that code (creating the pilot factory) when the definitions are loaded, but we want them to be as lazy as possible. By using the association syntax as I'd mentioned, it will ensure they're lazy.

Alternatively, you can use the block syntax:

```
factory :flight do
  pilot_id { FactoryGirl.create(:pilot).id }
end
```

Again, however, the previous association syntax is recommended.

Let me know how this goes.

**Comment by composerinteralia** [comment]
I'm going to assume the proposed solution worked. Feel free to reopen if this is still an issue.
