### ISSUE TITLE
RSpec startup - undefined method `to_json' for module `Enumerable' (NameError)

### ISSUE THREAD

**Issue by jgrosso** [thoughtbot/factory_bot_rails#184]
When RSpec starts, I receive the below error and stacktrace:

```
~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `to_json' for module `Enumerable' (NameError)
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:41:in `block (2 levels) in <top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:30:in `class_eval'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:30:in `block in <top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:29:in `each'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:29:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object.rb:12:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/core_ext/object.rb:12:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/configuration.rb:2:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/configuration.rb:2:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/railtie.rb:2:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/railtie.rb:2:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/engine.rb:1:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/engine.rb:1:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/application.rb:7:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails/application.rb:7:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails.rb:11:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/railties-4.2.5/lib/rails.rb:11:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails/railtie.rb:3:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails/railtie.rb:3:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails.rb:1:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails.rb:1:in `<top (required)>'
    from ~/careers/careers_api/spec/spec_helper.rb:19:in `require'
    from ~/careers/careers_api/spec/spec_helper.rb:19:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `require'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `block in requires='
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `each'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1295:in `requires='
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `each'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/configuration_options.rb:21:in `configure'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:101:in `setup'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
    from ~/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
    from ~/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `load'
    from ~/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `<main>'
    from ~/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from ~/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

There's none of my code in there (the offending line in spec_helper is `require 'factory_girl_rails'`); I dove into the library code and it wasn't very helpful.

Thanks!

**Comment by DevilalDheer** [comment]
Same issue during start rails server.

**Comment by composerinteralia** [comment]
I'm going to close this issue for now, but please feel free to open if the issue still exists on a more recent version of FactoryBot. I don't see anything obvious in the backtrace, so we would probably need a sample repo or some kind of reproduction script to be much help. Many thanks!
