### ISSUE TITLE
requiring `factory_girl_rails` failing

### ISSUE THREAD

**Issue by Mirv** [thoughtbot/factory_bot_rails#235]
Getting error with the gem, which I confirmed was installed with `bundle install`, then `bundle update` when the first didn't work.  Only saw two issues on here & neither of them worked.

Gemfile

```
...
group :development, :test do
...
  gem 'factory_girl'
  gem 'factory_girl_rails'
end
...
```
Console "gem list" output

```
factory_girl (4.8.0)
factory_girl_rails (4.8.0)
```

test_helper.rb
```
ENV["RAILS_ENV"] = "test"
require File.expand_path("../../config/environment", __FILE__)
require "rails/test_help"
require "minitest/rails"
require "minitest/rails/capybara"
require 'factory_girl'
require 'factory_girl_rails'  # Issue line, if I remove this everything is fine 
...
class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  fixtures :all
  # Add more helper methods to be used by all tests here...
end

class ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers
  include FactoryGirl::Syntax::Methods
end
```

Console error
```
(modulelessControllers) $ rails test test/integration/dashes_test.rb
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- factory_girl_rails (LoadError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
        from /home/ubuntu/workspace/basicB/test/test_helper.rb:8:in `<top (required)>'
        from /home/ubuntu/workspace/basicB/test/integration/dashes_test.rb:1:in `require'
        from /home/ubuntu/workspace/basicB/test/integration/dashes_test.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:11:in `require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:10:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/test_unit/minitest_plugin.rb:76:in `plugin_rails_init'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/minitest-5.10.1/lib/minitest.rb:80:in `block in init_plugins'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/minitest-5.10.1/lib/minitest.rb:78:in `each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/minitest-5.10.1/lib/minitest.rb:78:in `init_plugins'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/minitest-5.10.1/lib/minitest.rb:129:in `run'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/test.rb:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:138:in `require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:138:in `require_command!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:95:in `test'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by nimashariatian** [comment]
this gem has been renamed to factory_bot_rails

**Comment by Mirv** [comment]
Ty!
