### ISSUE TITLE
Multiple Tests Fail on Vanilla `bundle exec rake`

### ISSUE THREAD

**Issue by mzagaja** [thoughtbot/factory_bot_rails#355]
Initially on cloning the repo and attempting to run the test suite it failed for me. The issue was I had a `.railsrc` file that specified use of a template that attempted to do things that did not work in the context of this test suite. I was able to surmount this by moving `.railsrc` to `.backup_railsrc`. However I then get a new pile of failing tests to start with:

```
cucumber features/fixture_replacement_config.feature:18 # Scenario: Using Factory Bot and Factory Bot Rails with RSpec should generate a factory file
cucumber features/fixture_replacement_config.feature:35 # Scenario: Using Factory Bot and Factory Bot Rails with RSpec and suffix configuration should generate a factory file with suffix
cucumber features/fixture_replacement_config.feature:52 # Scenario: Using Factory Bot and Factory Bot Rails does not override a manually-configured factories directory using RSpec
cucumber features/generators.feature:12 # Scenario: The factory_bot_rails generators create a factory file for each model if there is not a factories.rb file
cucumber features/generators.feature:28 # Scenario: The factory_bot_rails generators add a factory in the correct spot
cucumber features/generators.feature:59 # Scenario: The factory_bot_rails generators use a custom template
cucumber features/load_definitions.feature:33 # Scenario: generate a Rails application and use factory definitions
cucumber features/load_definitions.feature:56 # Scenario: use custom definition file paths
cucumber features/load_definitions.feature:83 # Scenario: use 3rd-party factories with configured definition file paths
cucumber features/load_definitions.feature:118 #
```

A failed example might include:

```
+The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
+/Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:83:in `new'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:83:in `initialize'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:234:in `new'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:34:in `build'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler.rb:135:in `definition'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler.rb:101:in `setup'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 (RSpec::Expectations::ExpectationNotMetError)
features/fixture_replacement_config.feature:45:in `Then the output should contain "rspec-rails"'

expected "      create  \n      create  README.md\n      create  Rakefile\n      create  .ruby-version\n      ....rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'" to string includes: "rspec-rails"
Diff:
@@ -1,2 +1,216 @@
-rspec-rails
+      create
+      create  README.md
+      create  Rakefile
+      create  .ruby-version
+      create  config.ru
+      create  .gitignore
+      create  Gemfile
+         run  git init from "."
+Initialized empty Git repository in /Users/mzagaja/Developer/factory_bot_rails/tmp/aruba/testapp/.git/
+      create  package.json
+      create  app
+      create  app/assets/config/manifest.js
+      create  app/assets/javascripts/application.js
+      create  app/assets/javascripts/cable.js
+      create  app/assets/stylesheets/application.css
+      create  app/channels/application_cable/channel.rb
+      create  app/channels/application_cable/connection.rb
+      create  app/controllers/application_controller.rb
+      create  app/helpers/application_helper.rb
+      create  app/jobs/application_job.rb
+      create  app/mailers/application_mailer.rb
+      create  app/models/application_record.rb
+      create  app/views/layouts/application.html.erb
+      create  app/views/layouts/mailer.html.erb
+      create  app/views/layouts/mailer.text.erb
+      create  app/assets/images/.keep
+      create  app/assets/javascripts/channels
+      create  app/assets/javascripts/channels/.keep
+      create  app/controllers/concerns/.keep
+      create  app/models/concerns/.keep
+      create  bin
+      create  bin/bundle
+      create  bin/rails
+      create  bin/rake
+      create  bin/setup
+      create  bin/update
+      create  bin/yarn
+      create  config
+      create  config/routes.rb
+      create  config/application.rb
+      create  config/environment.rb
+      create  config/cable.yml
+      create  config/puma.rb
+      create  config/spring.rb
+      create  config/storage.yml
+      create  config/environments
+      create  config/environments/development.rb
+      create  config/environments/production.rb
+      create  config/environments/test.rb
+      create  config/initializers
+      create  config/initializers/application_controller_renderer.rb
+      create  config/initializers/assets.rb
+      create  config/initializers/backtrace_silencers.rb
+      create  config/initializers/content_security_policy.rb
+      create  config/initializers/cookies_serializer.rb
+      create  config/initializers/cors.rb
+      create  config/initializers/filter_parameter_logging.rb
+      create  config/initializers/inflections.rb
+      create  config/initializers/mime_types.rb
+      create  config/initializers/new_framework_defaults_5_2.rb
+      create  config/initializers/wrap_parameters.rb
+      create  config/locales
+      create  config/locales/en.yml
+      create  config/master.key
+      append  .gitignore
+      create  config/boot.rb
+      create  config/database.yml
+      create  db
+      create  db/seeds.rb
+      create  lib
+      create  lib/tasks
+      create  lib/tasks/.keep
+      create  lib/assets
+      create  lib/assets/.keep
+      create  log
+      create  log/.keep
+      create  public
+      create  public/404.html
+      create  public/422.html
+      create  public/500.html
+      create  public/apple-touch-icon-precomposed.png
+      create  public/apple-touch-icon.png
+      create  public/favicon.ico
+      create  public/robots.txt
+      create  tmp
+      create  tmp/.keep
+      create  tmp/cache
+      create  tmp/cache/assets
+      create  vendor
+      create  vendor/.keep
+      create  test/fixtures
+      create  test/fixtures/.keep
+      create  test/fixtures/files
+      create  test/fixtures/files/.keep
+      create  test/controllers
+      create  test/controllers/.keep
+      create  test/mailers
+      create  test/mailers/.keep
+      create  test/models
+      create  test/models/.keep
+      create  test/helpers
+      create  test/helpers/.keep
+      create  test/integration
+      create  test/integration/.keep
+      create  test/test_helper.rb
+      create  test/system
+      create  test/system/.keep
+      create  test/application_system_test_case.rb
+      create  storage
+      create  storage/.keep
+      create  tmp/storage
+      create  tmp/storage/.keep
+      remove  config/initializers/cors.rb
+      remove  config/initializers/new_framework_defaults_5_2.rb
+         run  bundle install
+Fetching gem metadata from https://rubygems.org/............
+Fetching gem metadata from https://rubygems.org/.
+Resolving dependencies....
+Using rake 13.0.1
+Using concurrent-ruby 1.1.5
+Using minitest 5.13.0
+Using thread_safe 0.3.6
+Using builder 3.2.3
+Using erubi 1.9.0
+Using mini_portile2 2.4.0
+Using crass 1.0.5
+Using rack 2.0.7
+Using nio4r 2.5.2
+Using websocket-extensions 0.1.4
+Using mini_mime 1.0.2
+Using arel 9.0.0
+Using mimemagic 0.3.3
+Using public_suffix 4.0.1
+Using io-like 0.3.0
+Using bindex 0.8.1
+Using msgpack 1.3.1
+Using bundler 2.0.2
+Using byebug 11.0.1
+Using regexp_parser 1.6.0
+Using childprocess 3.0.0
+Using coffee-script-source 1.12.2
+Using execjs 2.7.0
+Using method_source 0.9.2
+Using thor 0.20.3
+Using ffi 1.11.2
+Using rb-fsevent 0.10.3
+Using ruby_dep 1.5.0
+Using puma 3.12.1
+Using rubyzip 2.0.0
+Using tilt 2.0.10
+Using spring 2.1.0
+Using sqlite3 1.4.1
+Using turbolinks-source 5.2.0
+Using i18n 1.7.0
+Using nokogiri 1.10.5
+Using rack-test 1.1.0
+Using sprockets 3.7.2
+Using websocket-driver 0.7.1
+Using mail 2.7.1
+Using marcel 0.3.3
+Using addressable 2.7.0
+Using archive-zip 0.12.0
+Using bootsnap 1.4.5
+Using coffee-script 2.4.1
+Using uglifier 4.2.0
+Using rb-inotify 0.10.0
+Using selenium-webdriver 3.142.6
+Using turbolinks 5.2.1
+Using loofah 2.3.1
+Using xpath 3.2.0
+Using chromedriver-helper 2.1.1
+Using listen 3.1.5
+Using sass-listen 4.0.0
+Using rails-html-sanitizer 1.3.0
+Using capybara 3.29.0
+Using spring-watcher-listen 2.0.1
+Using sass 3.7.4
+Using tzinfo 1.2.5
+Using activesupport 5.2.3
+Using rails-dom-testing 2.0.3
+Using globalid 0.4.2
+Using activemodel 5.2.3
+Using jbuilder 2.9.1
+Using actionview 5.2.3
+Using actionpack 5.2.3
+Using activejob 5.2.3
+Using activerecord 5.2.3
+Using actioncable 5.2.3
+Using railties 5.2.3
+Using sprockets-rails 3.2.1
+Using activestorage 5.2.3
+Using actionmailer 5.2.3
+Using coffee-rails 4.2.2
+Using sass-rails 5.1.0
+Using web-console 3.7.0
+Using rails 5.2.3
+Bundle complete! 18 Gemfile dependencies, 78 gems now installed.
+Use `bundle info [gemname]` to see where a bundled gem is installed.
+         run  bundle exec spring binstub --all
+* bin/rake: Spring inserted
+* bin/rails: Spring inserted
+The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
+/Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:95:in `initialize'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:83:in `new'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:83:in `initialize'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:234:in `new'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:234:in `to_definition'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/dsl.rb:13:in `evaluate'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:34:in `build'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler.rb:135:in `definition'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler.rb:101:in `setup'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
+	from /Users/mzagaja/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
This is using ruby 2.6.5. 

If there is an easy thing to try or you want more logging I'm happy to help contribute that, but am not sure if I have time to put together a PR at this time. However, wanted to save the digging I did so far and share it in case anyone else encounters this or I have time in the future.

**Comment by composerinteralia** [comment]
Thanks for this report. I see `warn_for_outdated_bundler_version` in the final stack trace. Is it possible this is not working because you don't have bundler 2 installed?

**Comment by mzagaja** [comment]
Yeah, looks like this was fixed by https://github.com/thoughtbot/factory_bot_rails/commit/0f095984b52515f9247445e2cd6d37f1db1ecdd8. Given my fork is now behind by 31 commits (https://github.com/mzagaja/factory_bot_rails) looks like some updates just needed to be pushed so I'll close this. Thanks for the tip!
